trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.11"
  - script: |
      python -m pip install --upgrade pip
      pip install ruff pytest
    displayName: "Install dependencies"

  - script: |
      ruff check .
    displayName: "Lint"

  - script: |
      pytest
    displayName: "Test"
