"""
GitHub Actions Plugin for Antigravity Architect.

Provides templates and configuration for GitHub Actions, Issue Templates, PR Templates,
Funding configurations, and Copilot Instructions.
"""

import logging
from pathlib import Path
from typing import Any

from antigravity_architect.core.engine import AntigravityEngine

PLUGIN_DESCRIPTION = "GitHub Templates and Actions integration"

GITHUB_BUG_REPORT = """---
name: 🐛 Bug Report
about: Report a bug or unexpected behavior
title: "[BUG] "
labels: bug
assignees: ''
---

## 🐛 Bug Description
<!-- A clear description of what the bug is. -->

## 📋 Steps to Reproduce
1. Run `...`
2. Enter '...'
3. See error

## ✅ Expected Behavior
<!-- What you expected to happen. -->

## ❌ Actual Behavior
<!-- What actually happened. -->

## 🖥️ Environment
- **OS:** <!-- e.g., Windows 11, macOS, Ubuntu 22.04 -->
- **Python Version:** <!-- e.g., 3.12 -->

## 📜 Error Output
```
[Paste error here]
```
"""

GITHUB_FEATURE_REQUEST = """---
name: ✨ Feature Request
about: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: enhancement
assignees: ''
---

## ✨ Feature Description
<!-- A clear description of the feature you'd like. -->

## 🎯 Problem Statement
<!-- What problem does this feature solve? -->

## 💡 Proposed Solution
<!-- Describe how you envision this feature working. -->

## 🔄 Alternatives Considered
<!-- Any alternative solutions or workarounds? -->

## 📋 Checklist
- [ ] I have searched existing issues to ensure this is not a duplicate
"""

GITHUB_QUESTION = """---
name: ❓ Question
about: Ask a question about usage
title: "[QUESTION] "
labels: question
assignees: ''
---

## ❓ Question
<!-- What would you like to know? -->

## 📋 Context
<!-- What are you trying to accomplish? -->

## 🔍 What I've Tried
<!-- Have you checked the docs? Tried anything? -->
"""

GITHUB_PR_TEMPLATE = """## 📋 Description
<!-- Brief summary of the changes in this PR. -->

## 🔗 Related Issue
<!-- Link to related issue: Closes #123 -->

## 🏷️ Type of Change
- [ ] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] 💥 Breaking change
- [ ] 📚 Documentation update

## ✅ Checklist
- [ ] My code follows the project's coding style
- [ ] I have added/updated tests for my changes
- [ ] All tests pass
- [ ] I have updated documentation (if applicable)
- [ ] My commits follow Conventional Commits

## 🧪 How Has This Been Tested?
<!-- Describe how you verified your changes. -->
"""

GITHUB_FUNDING = """# Funding links
# github: [username]
# ko_fi:
# patreon:
# open_collective:
# custom: ["https://example.com"]
"""

GITHUB_ISSUE_CONFIG = """blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/{owner}/{repo}#readme
    about: Check the README for usage instructions
"""

GITHUB_CI_TEMPLATE = """name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
"""

GITHUB_COPILOT_INSTRUCTIONS = """# GitHub Copilot Instructions

## Project Context

This project uses **{tech_stack}** as its core technology stack. All code should follow the conventions and patterns established in the existing codebase.

## Development Workflow

### Before Making Changes
1. Check `docs/imported/` for project-specific documentation
2. Review `context/raw/` for original specifications
3. Consult `.agent/rules/` for coding standards and conventions
4. Read `CONTRIBUTING.md` for contribution guidelines

### Testing
```bash
# Run tests before committing
# [Add your test command here]
```

### Code Quality
```bash
# Lint and format code
# [Add your linting commands here]
```

## Project-Specific Patterns

### File Organization
- Source code: `src/`
- Tests: `tests/`
- Documentation: `docs/`
- Configuration: Root directory

### Architecture Rules
- Ensure low coupling between modules
- Keep functions small and focused
- Prefer early returns

## Common Tasks
- **Adding a rule**: Create a `.md` file in `.agent/rules/`
- **Adding a skill**: Create a script in `.agent/skills/`

_Generated by Antigravity Architect_
"""


def on_generation_complete(
    project_name: str,
    base_dir: str,
    final_stack: list[str],
    safe_mode: bool,
    **kwargs: Any,  # noqa: ARG001
) -> None:
    """Generates GitHub-specific templates and workflows."""
    logging.debug(f"GitHub Plugin: Generating configuration for {project_name}")

    github_dir = Path(base_dir) / ".github"
    workflow_dir = github_dir / "workflows"
    issue_template_dir = github_dir / "ISSUE_TEMPLATE"

    # Create directories
    AntigravityEngine.create_folder(str(workflow_dir))
    AntigravityEngine.create_folder(str(issue_template_dir))

    templates = {
        issue_template_dir / "bug_report.md": GITHUB_BUG_REPORT,
        issue_template_dir / "feature_request.md": GITHUB_FEATURE_REQUEST,
        issue_template_dir / "question.md": GITHUB_QUESTION,
        issue_template_dir / "config.yml": GITHUB_ISSUE_CONFIG,
        github_dir / "PULL_REQUEST_TEMPLATE.md": GITHUB_PR_TEMPLATE,
        github_dir / "FUNDING.yml": GITHUB_FUNDING,
        github_dir / "copilot-instructions.md": GITHUB_COPILOT_INSTRUCTIONS.format(tech_stack=", ".join(final_stack)),
        workflow_dir / "ci.yml": GITHUB_CI_TEMPLATE,
    }

    for path, content in templates.items():
        AntigravityEngine.write_file(str(path), content, exist_ok=safe_mode)
